#!/usr/bin/sh

for arg in "$@"; do
    if [ -f "$arg" ]; then
        arg_noext="${arg%%\.*}"
        echo "${arg} -> ${arg_noext}.pdf"
        arg_dvi="${arg_noext}.dvi"
        groff -Kutf8 -Tdvi -mpdfmark -mec -ms "${arg}" > "${arg_dvi}"
        dvipdfm -cz 9 "${arg_dvi}"
        #rm "${arg_dvi}"
    fi
done

