#!/bin/sh
OPTION=$(printf "Cancel\nTurn off\nReboot\n" | dmenu -p "Action:")

case $OPTION in
    "Turn off")
        poweroff
        ;;
    "Reboot")
        reboot
        ;;
    **)
        ;;
esac

