#!/bin/sh

SOUNDMASTER=$(pactl list sinks | grep 'Active Port' | awk -F '-' '{print $3}')
VOLUME=$(pactl list sinks | grep '^\s*Volume' | awk '{print $5}')

case "${SOUNDMASTER}" in
"speaker")
    ICON='\U0001F50A'
    ;;
"headphones")
    ICON='\U0001F3A7'
    ;;
*)
    ;;
esac

env printf "${ICON}${VOLUME}"

